### ISSUE TITLE
How to refresh the PDF View in doc-browser?

### ISSUE THREAD

**Issue by boesiii** [pymupdf/PyMuPDF-Utilities#1]
Hello.  I am using your doc-browser as a lightweight pdf editor.  I have added buttons to rotate a page and also reorder the pages but after I click my buttons I don't see the edits because I have to refresh the view.  Is there a simple way to refresh the opened PDF?
```
elif is_Rotate180(btn):
        doc[0].setRotation(90)    
        doc.save(doc.name, incremental = True)
elif is_ReorderPages(btn):
        doc.movePage(1, 0)
        doc.save(doc.name, incremental = True)
```

**Comment by JorjMcKie** [comment]
As far as I remember this script, I am using a mechanism for performance improvement, employing `DisplayList` objects. This type of object _preprocesses_ a page for later image creation and text extraction.
You should change that to just directly using ``page.getPixmap`` for the page. Then the pixmap will always reflect the current (e.g. rotated) page image.

Deleting use of display lists is also required when the _page tree_ is rebuilt, as it always happens if you use any of the methods `copyPage`, `movePage`, `deletePage`, `deletePageRange ` or ``select``. Actually all of them internally use `select`.

My array of stored display lists obviously gets invalidated by all of these actions - the item index in this array equals the page number.

If you want, you of course can also "refresh" the display list array after every of your changes: for a single page's change, just re-create its display list entry, for page tree changes, re-initialize the whole array.

As an overall recommendation, postpone the `doc.save` to the end of the program. Your changes are all available in your script without this happening.

**Comment by JorjMcKie** [comment]
BTW if you do a `doc.save` **once** only, the size of the delta information (reflecting `incremental`) will be a lot smaller than with multiple single saves.

**Comment by boesiii** [comment]
Thanks.  I tried simply replacing DisplayList with Pixmap but got some errors.  I will have to learn more about the code.

**Comment by JorjMcKie** [comment]
What I meant was this:

- If you updated one page (new rotation or whatever), then do this: `dlist_tab[pno] = doc[pno].getDisplayList()` immediately after that.

- If you change the **_page tree_** (`movePage`, etc.), then do simply this: `dlist_tab = [None] * len(doc)` - just as it was done at start of the program. This will force a new display list being built for every page that will be visited hereafter.

**Comment by boesiii** [comment]
Works! Thanks.
