### ISSUE TITLE
error with page.get_textbox

### ISSUE THREAD

**Issue by Larbo53** [pymupdf/PyMuPDF-Utilities#13]
Good morning,

to identify a supplier, I use an sql query to extract the rectangle containing the supplier identifier.
The rectangle (zone : REC) is stored in a 'blob' zone.
The query returns a string which is not suitable for the page.get_textbox(rec) command which requires rec to be a list

query :
sql_rect="SELECT Vendor_Code,REC FROM Schema_recup_Data WHERE Column_Name='Customer_ID'"
    curs1.execute(sql_rect)
    for row in curs1:
Identifier=page.get_textbox(row[1])

error returned :
 File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fitz/fitz.py", line 903, in __init__
    raise ValueError("bad Rect: sequ. length")
ValueError: bad Rect: sequ. length

What is the solution?

thanks for your feedback.

Best regards.

Translated with www.DeepL.com/Translator (free version)

**Comment by JorjMcKie** [comment]
Using ordinary mail because my internet connection doesn’t work again.

You must pass a Python sequence of 4 floats to any PyMuPDF function that expects a rectangle – not a string.
Thos 4 floats must define the coordinates of the top-left and the bottom-right coordinates, respectively, of that rectangle.
Depending on how those coordinates are defined in you string, they may not meet this requirement (and instead might specify the bottom-left and the top-right corner). You must figure this out.
If you are having the wrong coordinate specification, you must first transform the rect before using it. This can be done by multiplying the rect with the matrix page.transformation_matrix.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
Von: Larbo53 ***@***.***>
Gesendet: Monday, August 2, 2021 5:58:17 AM
An: pymupdf/PyMuPDF-Utilities ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [pymupdf/PyMuPDF-Utilities] error with page.get_textbox (#13)


Good morning,

to identify a supplier, I use an sql query to extract the rectangle containing the supplier identifier.
The rectangle (zone : REC) is stored in a 'blob' zone.
The query returns a string which is not suitable for the page.get_textbox(rec) command which requires rec to be a list

query :
sql_rect="SELECT Vendor_Code,REC FROM Schema_recup_Data WHERE Column_Name='Customer_ID'"
curs1.execute(sql_rect)
for row in curs1:
Identifier=page.get_textbox(row[1])

error returned :
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fitz/fitz.py", line 903, in init
raise ValueError("bad Rect: sequ. length")
ValueError: bad Rect: sequ. length

What is the solution?

thanks for your feedback.

Best regards.

Translated with www.DeepL.com/Translator<http://www.DeepL.com/Translator> (free version)

**Comment by Larbo53** [comment]
good idea.
Thank you for your quick response.
Greetings from France.

**Comment by JorjMcKie** [comment]
Salu du Venezuela
