### ISSUE TITLE
demo/text2pdf.py   

### ISSUE THREAD

**Issue by normanlorrain** [pymupdf/PyMuPDF-Utilities#4]
## Describe the bug (mandatory)
It looks like the interface to _getCharWidths() has changed.  
`PDF conversion results for file 'test.file':
1 lines read, 1 lines written, 61 lines per page.
test.file.pdf contains 1 pages.
Traceback (most recent call last):
  File "PyMuPDF-Utilities-master\PyMuPDF-Utilities-master\demo\text2pdf.py", line 73, in <module>
    fwidths = doc._getCharWidths("Helvetica")   # get glyph widths of font
TypeError: _getCharWidths() missing 4 required positional arguments: 'bfname', 'ext', 'ordering', and 'limit'`

## To Reproduce (mandatory)
>echo "Test string" > test.txt
>python PyMuPDF-Utilitites/demo/text2pdf test.txt

## Expected behavior (optional)
Creation of PDF from input file. 

## Your configuration (mandatory)
- Windows 10 64 bit
- Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32
- pymupdf-1.16.10 -- PyMuPDF-1.16.10-cp38-none-win_amd64.whl
- PyMuPDF-Utilities commit: 7604352

**Comment by JorjMcKie** [comment]
Thanks for tracing this.
During a productive phase I created several example scripts. Which has turned into some kind of a curse over time, because PyMuPDF has evolved and changed some of its APIs - as you noted.
I must say, I am unable to revisit all those examples over and over again for every new version.

So I would be grateful if you could adjust the script and submit a PR, which I would gladly incorporate ... thank you!

**Comment by normanlorrain** [comment]
Glad to help.  Nice library!
